notifications:
  email:
    recipients:
      -reywongc@163.com
  on_success: change
  on_failure: always

language: java
jdk:
#  - oraclejdk8
  - oraclejdk7
script:
  - travis_retry mvn -B clean
  - travis_retry mvn -B package findbugs:findbugs jacoco:report coveralls:report
#after_success:
#    - mvn sonar:sonar